### PR TITLE
The website crapto1.netgarage.org is down

### PR DESCRIPTION
**Pull request by arlion-dev**
The website crapto1.netgarage.org is down, so we can't compile the patch...

### CODE REVIEW

**Comment by dimitrire** [comment]
Hello, have you found a solution for netgarage ?

**Comment by ghost** [comment]
> Hello, have you found a solution for netgarage ?

I think we have to download it manually but i'm not sure how to apply it.

**Comment by ilyesAj** [comment]
this is an alternative link for the two tar :
http://www2.vaneay.fr/mifare/

**Comment by petergozer** [comment]
Does any one know how to install the files manually? cant figure it out by myself

**Comment by kevincastejon** [comment]
> 
> 
> this is an alternative link for the two tar :
> http://www2.vaneay.fr/mifare/

This link is now down too..

**Pull request closed without merging**
